on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          podman run --privileged --rm -it -v /dev:/dev -v $PWD:/code -w /code registry.fedoraproject.org/fedora:rawhide bash - <<HERE
          dnf install -y kiwi-cli
          cd /code
           ./kiwi-build --kiwi-file=Fedora-msm8916.kiwi --image-type=oem --image-profile=MSM8916-Disk --output-dir ./outdir
          HERE
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fedora-Remix-Mobility-SDM845-OnePlus
          path: ./outdir-build/Fedora-Remix-Mobility.tar.xz
          compression-level: 0
